export const CREATE_LAYERS_SUCCESS="CREATE LAYERS SUCCESS"
export const GET_LAYERS_SUCCESS="GET LAYERS SUCCESS"
export const GET_FIELD_DATA="GET FIELD DATA"
export const GET_GROP_TYPES="GET CROP TYPES"
export const GET_FIELD_DATA_FAIL="GET FIELD DATA FAIL"
export const GET_ALL_FIELD_DATA="GET ALL FIELD DATA"
export const GET_GROUP_FIELD_DATA="GET GROUP FIELD DATA"
export const GET_ALL_FIELD_DATA_INITIATED="GET ALL FIELD DATA INITIATED"
export const FORECAST_FIELD_ID="FORECAST FIELD ID"

export const GET_GRID_DATA_FAIL="GET GRID DATA FAIL"
export const GET_ALL_GRID_DATA="GET ALL GRID DATA"

export const GET_kATOR_DATA_FAIL="GET kATOR DATA FAIL"
export const GET_ALL_KATOR_DATA="GET ALL kATOR DATA"

export const GET_FCAST_DATA_FAIL="GET FCAST DATA FAIL"
export const GET_ALL_FCAST_DATA="GET ALL FCAST DATA"

export const INITIATE_GET_NDVI_CHANGE="INITIATE GET NDVI CHANGE"
export const GET_NDVI_CHANGE_SUCCESS="GET NDVI CHANGE SUCCESS"
export const GET_NDVI_CHANGE_FAIL="GET NDVI CHANGE FAIL"

export const INITIATE_GET_WEEKLY_DATA="INITIATE GET WEEKLY DATA"
export const GET_WEEKLY_DATA_SUCCESS="GET WEEKLY DATA SUCCESS"
export const GET_WEEKLY_DATA_FAIL="GET WEEKLY DATA FAIL"

// ONE ACRE FUND TYPES
export const GET_LAST_VISITS="GET LAST VISITS"
