export const CREATE_LAYERS_SUCCESS="CREATE LAYERS SUCCESS"
export const GET_LAYERS_SUCCESS="GET LAYERS SUCCESS"
export const GET_FIELD_DATA="GET FIELD DATA"
export const GET_FIELD_DATA_FAIL="GET FIELD DATA FAIL"
